# Generated by Django 6.0.1 on 2026-01-17 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=25)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='manager.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
