# Generated by Django 6.0.1 on 2026-01-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_user_role_remove_user_email_task_delete_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_owner',
        ),
        migrations.AddField(
            model_name='task',
            name='task_owner',
            field=models.ManyToManyField(related_name='owner', to='manager.user'),
        ),
    ]
